name: Assertions

on:
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Lint JavaScript
        run: npx eslint '**/*.{js,ts}' --config=.eslintrc.js

      - name: Take Screenshots
        run: npm start
